name: Branch Protection

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch rules
        run: |
          BASE_BRANCH="${{ github.base_ref }}"
          HEAD_BRANCH="${{ github.head_ref }}"

          if [ "$BASE_BRANCH" = "main" ] && [{ ! "$HEAD_BRANCH" =~ "^feature/" }] && [{ ! "$HEAD_BRANCH" =~ "^hotfix/" }] && [{ ! "$HEAD_BRANCH" =~ "^release/" }]; then
            echo "Error: Only 'develop', 'hotifx/*' and 'release/*' branch can be merged into 'main'"
            exit 1
          fi

          if [ "$BASE_BRANCH" = "develop" ] && [{ ! "$HEAD_BRANCH" =~ "^feature/" }] && [{ ! "$HEAD_BRANCH" =~ "^hotfix/" }]; then
            echo "Error: Only 'feature/*' and 'hotifx/*' branches can be merged into 'develop'"
            exit 1
          fi
