name: Deploy Documentation Website

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies (documentation only)
        run: npm ci --prefix=src/routes

      - name: Build documentation website
        run: npm run build:docs

      - name: Move documentation website
        run: npm run build:docs

      - name: Move documentation website
        run: |
          git checkout -B main
          git add -A
          git commit -m "Deploy documentation website"
          git push origin main

      - name: Configure GitHub Pages (in GitHub Settings)
        uses: actions/github-script@v6
        with:
          script: |
            github.context.payload.repository.default_branch = 'main';
            github.rest.repos.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              default_branch: 'main'
            });
